name: SkinHub
version: '${project.version}'
main: com.zeroends.skinhub.SkinHub
api-version: '1.21'
author: ZeroEnds
description: Web-based skin management for your server.
softdepend: [SkinsRestorer]
commands:
  skinhub:
    description: SkinHub main command.
    aliases: [skin]
    usage: /<command> [pin]
permissions:
  skinhub.use:
    description: Allows using the /skinhub pin command.
    default: true
