name: SkinHub
version: '1.0.0'
main: com.zeroends.skinhub.SkinHub
api-version: '1.21'
author: ZeroEnds
description: Web-based skin management for your server.
softdepend: [SkinsRestorer]
commands:
  skin:
    description: SkinHub main command.
    aliases: [skinhub]
    usage: /<command> [pin]
permissions:
  skinhub.use:
    description: Allows using the /skin pin command.
    default: true
